#!/bin/bash
set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
mkdir -p "$SCRIPT_DIR/keys"

# 1. JWT Ed25519 key pair (auth service)
openssl genpkey -algorithm Ed25519 -out "$SCRIPT_DIR/keys/auth-private.pem"
openssl pkey -in "$SCRIPT_DIR/keys/auth-private.pem" -pubout -out "$SCRIPT_DIR/keys/auth-public.pem"
echo "Generated Ed25519 key pair in deploy/keys/"
echo "  Private: keys/auth-private.pem"
echo "  Public:  keys/auth-public.pem"

# 2. ECDSA P-256 board signing key (bulletin-board service)
openssl ecparam -genkey -name prime256v1 -noout -out "$SCRIPT_DIR/keys/board-signing.pem"
echo "Generated ECDSA P-256 signing key: keys/board-signing.pem"

# 3. Dev trustee keys (tally service requires at least one)
# Uses the Ristretto255 base point as a dev-only trustee verification key.
# Production uses actual DKG output from the key ceremony.
RISTRETTO_BASEPOINT="e2f2ae0a6abc4e71a884a961c500515f58e30b6aa582dd8db6a65945e08d2d76"
echo "[{\"index\":1,\"key\":\"$RISTRETTO_BASEPOINT\"}]" > "$SCRIPT_DIR/keys/trustee-keys.json"
echo "Generated dev trustee keys: keys/trustee-keys.json"

# 3. Generate .env with all required secrets
ENV_FILE="$SCRIPT_DIR/.env"
cat > "$ENV_FILE" <<EOF
# Generated by generate-dev-keys.sh — local development only.
# DO NOT use these values in production.

# Database (separate passwords for layer isolation)
POSTGRES_PASSWORD_BB=$(openssl rand -hex 16)
POSTGRES_PASSWORD_COLLECTION=$(openssl rand -hex 16)

# API keys
INTERNAL_API_KEY=$(openssl rand -hex 32)
SESSION_API_KEY=$(openssl rand -hex 32)
BULLETIN_BOARD_API_KEY=$(openssl rand -hex 32)
ACTIVE_SET_API_KEY=$(openssl rand -hex 32)
CEREMONY_API_KEY=$(openssl rand -hex 32)

# HMAC keys
EGN_HMAC_KEY=$(openssl rand -hex 32)
HISTORY_HMAC_KEY=$(openssl rand -hex 32)

# Verification
VERIFICATION_API_KEY=$(openssl rand -hex 32)

# Signing key path (mounted in container)
SIGNING_KEY_PATH=/keys/board-signing.pem
EOF

echo "Generated .env with random secrets: deploy/.env"
